### ISSUE TITLE
Link til visning av driftsmeldinger i README

### ISSUE THREAD

**Issue by oledid** [ks-no/fiks-driftsmeldinger#5]
Heisann

Når jeg googler "fiks driftsmeldinger" for å se driftsmeldinger får jeg opp denne fordi github ranker høyt. Det er likevel ikke lett å finne faktisk visning av driftsmeldinger. Hvor deployer dere driftsmeldingene? Vært kjekt med en link til visning i dette github repoet.

Mvh

**Comment by andersflemmen** [comment]
Hei, takk for tilbakemeldingen! 

Driftsmeldingene som er definert her vil dukke opp som bannere øverst på sine respektive sider, f.eks. min.kommune.no. Ellers kan du finne driftsmeldinger på https://status.fiks.ks.no. Har lagt til en lenke øverst i readme, og vi har i tillegg gjort noen endringer med statussiden som forhåptenligvis gjør at den scorer høyere på Google-søk.
